name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: JD_Profile/aws-eks-ha-project

      - name: Terraform Validate
        run: terraform validate
        working-directory: JD_Profile/aws-eks-ha-project

      - name: Terraform Plan
        run: terraform plan
        working-directory: JD_Profile/aws-eks-ha-project
